### ISSUE TITLE
Branches are identical, nothing to compare (clarification)

### ISSUE THREAD

**Issue by albertz** [adobe/sizewatcher#79]
I want to use sizewatcher to disallow any Git pushes to some GitHub repo which contain too large files.
I am using GitHub Actions.

### Expected Behaviour

It compares the sizes before the push and after the push.

### Actual Behaviour

I just get the message:
```
Checking out git branches...
Branches are identical, nothing to compare (master=master). Compare selected branches using 'sizewatcher <before> <after>'.
```

### Reproduce Scenario (including but not limited to)

GitHub Action workflow file: https://github.com/rwth-i6/returnn-experiments/blob/master/.github/workflows/sizewatcher.yml
Configuration: https://github.com/rwth-i6/returnn-experiments/blob/master/.sizewatcher.yml

### Discussion

I'm actually not so sure if this is always well defined. Is it always clear in a GitHub Action workflow what commits have been added?

**Comment by albertz** [comment]
Ok, after thinking about this, maybe what I want cannot really be done for the master branch directly. The GitHub action would execute only after the push has completed, but then it is already too late. I want that such pushes are forbidden. Basically like a pre-receive-hook which stops the push when there are too large files.

I assume your workflow is that you only have this for PRs, and no direct pushes to the master branch are allowed? Then you enforce that the checks are passing for the PR, and that way you make sure that big files are not ending up in the master branch?

Maybe you have some other idea to what I want?

In any case, I think it would be helpful to clarify this more in the README.

**Comment by alexkli** [comment]
Sorry for the delayed response - I was missing notifications for this repository.

You are correct that the current state is optimized for a PR workflow and checks/comments in a PR after a push to a remote repository.

In general I would say that a completely automatic behavior such as blocking on a pre-receive-hook might be too strict, if humans cannot override it. Often times it might be ok to live with a size increase, or the tool is calculating not 100% correctly. That's why I designed it for the PR flow where it's visible to the users and they can choose whether they ignore it or not.

**Comment by alexkli** [comment]
@albertz 

I also looked at your repo links and history and it seems you never ran the sizewatcher on a PR, but just on direct commits to main. Then this output is totally expected, as it would only see the main branch.

FWIW, you can pass the exact commits you want to compare as arguments to sizewatcher:

```
sizewatcher -h
Usage: sizewatcher [<options>] [<before> [<after>]]

Arguments:
  <before>   Before branch/commit for comparison. Defaults to default branch or main/master.
  <after>    After branch/commit for comparison. Defaults to current branch.

Options:
  -h     Show help
```

So if you really want to, you could write a wrapper script that figures out the previous and current commit and pass those commit shas as `<before>` and `<after>` to the sizewatcher cli, for example:

```
npx sizewatcher abc123 def456
```

Though you would have to parse the console output in some form if you wanted to make an automated decision. The exit code is not based on the results - it would only fail with non-zero exit code in case something failed like reading the config file etc. I would not want to change the default here, as that would break the CI jobs (if the command fails, a sizewatcher CI job would fail by default). But this might be an option on the command line. Feel free to create an issue for that if you think that would be helpful.

**Comment by alexkli** [comment]
Closing this issue as it was more question. As mentioned feel free to open a new one for specific needs!
